### ISSUE TITLE
Tab height is size of largest tab Large Whitespace - Bug

### ISSUE THREAD

**Issue by stephanoparaskeva** [netguru/sticky-parallax-header#92] opened 2020-05-12 03:47 UTC
This is related to the previous issue. As all scrolls have same ref and are dependent on eachother, it means if you have multiple tabs with different size content, the content of the large tab is the size of the container leaving massive amounts of whitespace
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40718272/81636377-9e52d080-940b-11ea-83d8-5595efd3bfc4.gif)

**Comment by IdaszakDaniel** [comment] 2020-05-12 10:20
Duplicate of #63

**Closed by IdaszakDaniel** 2020-05-12 10:20 UTC
