### ISSUE TITLE
Is there an onDisplayedTabChanged event on TabbedHeader?

### ISSUE THREAD

**Issue by Kleinhummel** [netguru/sticky-parallax-header#128] opened 2020-09-03 16:18 UTC
An event would be cool, that is called every time the displayed tab is changed. It could be named `onTabChanged` and the argument for the handler function could be the index of the tab that is currently displayed.

**Comment by DimitrisTzimikas** [comment] 2020-09-09 12:46
@Kleinhummel  Check that
`<StickyParallaxHeader
          onChangeTab={(i) => {
            console.log(i);
          }}......`

**Comment by pi0trpietruszewski** [comment] 2020-09-24 10:44
> @Kleinhummel Check that
> `<StickyParallaxHeader onChangeTab={(i) => { console.log(i); }}......`
Yes, use this prop
` onChangeTab: (  from: number;
  i: number;
  ref: any;) => void;`

**Comment by pi0trpietruszewski** [comment] 2020-09-24 13:42
I am closing issue, if it won't help feel free to reopen issue

**Closed by pi0trpietruszewski** 2020-09-24 13:42 UTC
Labels: awaiting feedback

**Comment by dungdt-pnc** [comment] 2020-12-26 05:18
its doesnt work! Please check again @pi0trpietruszewski

**Comment by Vn-ChemGio** [comment] 2021-04-01 14:24
> 
> 
> > @Kleinhummel Check that
> > `<StickyParallaxHeader onChangeTab={(i) => { console.log(i); }}......`
> 
> Yes, use this prop
> 
> ` onChangeTab: ( from: number; i: number; ref: any;) => void;`
> 
>     * from: index of source
> 
>     * i: current tab
> 
>     * ref: reference to current tab
you missing {  } in param list
Correct:  onChangeTab: ({ from: number; i: number; ref: any;}) => void;

**Comment by fedenelli** [comment] 2021-09-21 00:08
This method is failing for me too.

I am trying to check when a user navigates between tabs to update each tab's content, but onChangeTab does not fire.

My props looks like this

```
tabs={[
        {
          title: 'Account',
          content: <Account focus={tab === 1} />,
        },
        {
          title: 'Movements',
          content: <Movements focus={tab === 1} />,
        },
        {
          title: 'Redeems',
          content: <Redeems focus={tab === 2} />,
        },
]}
 onChangeTab={a => {
        console.log('CHANGED TAB', a);
        return setTab(a.i);
}}
```

**Comment by fedenelli** [comment] 2021-09-21 00:34
After inspecting the package, I can confirm that this is solved in the repo but the fix is not available in the latest npm release.

**Comment by JayantJoseph** [comment] 2022-04-01 09:57
onChangeTab is not firing for me either. I tried using:
```
<StickyParallaxHeader
          headerType="TabbedHeader"
```
